language: rust
rust:
  - nightly
  - beta
  - stable
env:
  - GTK=3.4
  - GTK=3.18
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
  - rustc --version
  - cargo install clippy || touch clippy_failed
  - if [ ! -f clippy_failed ]; then cargo clippy; fi
  - cargo build
  - cargo test -- --test-threads 1
